name: mitso
description: MITSO - class schedule

version: 3.0.5

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.16.1
  firebase_messaging: ^6.0.9
  firebase_analytics: ^5.0.11
  firebase_crashlytics: ^0.1.2+5
  firebase_remote_config: ^0.3.0+1
  firebase_admob: ^0.9.0+10
  http: ^0.12.0+4
  html: ^0.14.0+3
  shared_preferences: ^0.5.6+1
  pull_to_refresh: ^1.5.8
  url_launcher: ^5.4.1
  flutter_local_notifications: ^1.1.5+1
  rxdart: ^0.23.1
  package_info: ^0.4.0+13
  vibration: ^1.2.2
  sensors: ^0.4.1+7
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/chip.png

  fonts:
    - family: Montserrat-Bold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: Montserrat-SemiBold
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf
    - family: Montserrat-Regular
      fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
    - family: Montserrat-Medium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: Montserrat-Light
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf